kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: $IMAGES
  name: $IMAGES
  namespace: sango-mall
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGES
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: $IMAGES
    spec:
      nodeName: k8s-3
      imagePullSecrets:
        - name: aliyunacr-secret
      containers:
        - image: '$REGISTRY/$ALIYUNACR_NAMESPACE/$IMAGES:$BUILD_NUMBER'
          name: app
          ports:
            - containerPort: $JAR_PORD
              protocol: TCP
          resources:
            limits:
              cpu: '0.3'
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: $IMAGES
  namespace: sango-mall
spec:
  ports:
  - port: $JAR_PORD
    protocol: TCP
    targetPort: $JAR_PORD
  selector:
    app: $IMAGES
  type: ClusterIP
